### ISSUE TITLE
Failed to minify the code from this file: ./node_modules/keytar/lib/keytar.js:12

### ISSUE THREAD

**Issue by allemanfredi** [atom/node-keytar#139]
I'm trying to develop a react application by using this module but when i run the following command: `npm run build` i receive this error: Failed to minify the code from this file: ./node_modules/keytar/lib/keytar.js:12

**Comment by shiftkey** [comment]
@allemanfredi what does your `npm run build` command do exactly? And what version of `keytar` are you using?

**Comment by shiftkey** [comment]
@allemanfredi this still doesn't seem like it's something that `keytar` has much control over.

Any clue _why_ the minification step doesn't like this code?

https://github.com/atom/node-keytar/blob/v4.3.0/lib/keytar.js#L9-L23

The module itself hasn't been updated since December 2017.

**Comment by vladimiry** [comment]
@allemanfredi 

> Failed to minify the code from this file: ./node_modules/keytar/lib/keytar.js:12

I guess it could be because `uglify` minificator is not able to handle the es6+ code by default. But `create-react-app` project [switched](https://github.com/facebook/create-react-app/pull/5026) to `terser` based javascript code minification since v2 release, so I'd recommend updating to a recent `create-react-app` version and giving it another try.

Alternatively try manually converting the code on the errored line to es5 syntax and then run your stuff (I guess there might be something like arrow function, so turn it to old fashion function). This would allow narrowing down the scope.

**Comment by shiftkey** [comment]
Closing this out due to a lack of information, or a runnable example being provided to illustrate the issue and how it relates to keytar...
