### ISSUE TITLE
keytar doesn't work on docker ubuntu

### ISSUE THREAD

**Issue by samuela** [atom/node-keytar#166]
It produces a rather odd error:
```
Error: /nuvemfs/node_modules/keytar/build/Release/keytar.node: invalid ELF header
    at Object.<anonymous> (/nuvemfs/node_modules/keytar/lib/keytar.js:1:76)
```

**Comment by ncortines** [comment]
seems like you compiled it for a different architecture

**Comment by shiftkey** [comment]
> seems like you compiled it for a different architecture

This is the essence of the problem. Without more information on reproducing the issue (which architecture you were running it with) as well as details about the install time experience (which version of Node, what happens when you did an `npm install`) it's really hard to say what the root cause is to confirm this.

**Comment by samuela** [comment]
I'm no longer using keytar.

**Comment by AdityaHirapara** [comment]
@samuela what did you use as an alternative here?

**Comment by bitclaw** [comment]
Happens for me on Ubuntu 20.04 with the following NPM dependencies:

Electron:
^11.4.2
Node:
12.18.3
Keytar:
^7.7.0

I am building an Electron app with Vue 3. Happens sometimes when I run the following command:

"electron:serve": "vue-cli-service electron:serve",

So to solve it I do an rm -rf node_modules then run yarn install and it resolves itself. I think what actually solves it the post install app-deps command:

"postinstall": "yarn run lint:fix;yarn run requirements:check;electron-builder install-app-deps",
