### ISSUE TITLE
Detect and use KDE instead of GNOME

### ISSUE THREAD

**Issue by jalcine** [atom/node-keytar#17]
It's a bit biased to assume everyone uses GNOME, in my opinion. If willing to be accepted, I can try to provide a patch that'd allow for KDE's password manager, KWallet, to be used over GNOME's keyring.

**Comment by hbetts** [comment]
As a KDE desktop user, supporting KDE would be appreciated.

**Comment by Marsup** [comment]
I'll add my voice to this issue, slack app stopped working for me because it couldn't find libgnome-keyring.so.0.

**Comment by paulcbetts** [comment]
@jalcine I think we'd totally be into that patch, if you can make it support both (and know when to pick the right one)

**Comment by jalcine** [comment]
@paulcbetts Thanks! I'll pull something together when I get some time.

**Comment by belldandu** [comment]
@paulcbetts it should be impossible to have libgnome-keyring and kdewallet(aka kwallet) on the same system since they conflict with each other and each belong to their respective desktop environments.

I'm thinking about looking into this myself and providing a patch since its kind of annoying being unable to save passwords in the brave browser without having to install and extra password manager and/or installing a gnome library that i don't want since it conflicts with my currently installed password manager.

**Comment by belldandu** [comment]
Well here is kwallet.h https://api.kde.org/4.x-api/kdelibs-apidocs/kdeui/html/kwallet_8h_source.html

**Comment by belldandu** [comment]
ATM i see no way to detect kwallet

**Comment by paulcbetts** [comment]
@belldandu If I had to guess, it _probably_ at the end of the day puts itself up as a DBus service

**Comment by thomasjo** [comment]
@paulcbetts Good guess. Evidence can be seen [here](https://quickgit.kde.org/?p=kde-runtime.git&a=blob&h=be59cef53bfd164a98885698cc241dc5f8232be6&f=kwalletd%2Fkwalletd.cpp&o=plain).

**Comment by jathpala** [comment]
Hi all. I've just submitted a pull request for some code that tries to implement this feature.

Various environment variable are used to guess which backend to use and requests are then passed to either gnome-keyring or kwallet (for KF5).

I've done some testing of this code but would appreciate any further testing people are able to do (especially from GNOME and other desktops).

Any feedback and suggestions are much appreciated.
