### ISSUE TITLE
Build on Mac for Windows

### ISSUE THREAD

**Issue by brightsider** [atom/node-keytar#171]
Is it available?
I'm created a build on Mac, but getting error keytar.node is not a valid Win32 application.
When builded on Windows error gone.

**Comment by ncortines** [comment]
keytar is a **native** node module - you can't cross-compile it

**Comment by shiftkey** [comment]
There are also `prebuild` packages with each release that contain the native binary so that you could _package_ for Windows without needing to _compile_ for Windows. But that depends on the downstream tools for packaging and ensuring they leverage `prebuild` correctly.

It's hard to suggest alternatives without more information, but as @ncortines said you cannot cross-compile native node modules.

**Comment by brightsider** [comment]
Thanks.
