### ISSUE TITLE
libsecret to use ZX2C4's pass 

### ISSUE THREAD

**Issue by helionmelion** [atom/node-keytar#230]
## Summary

I sugested to mailspring email client team to consider implement an option to use "pass" (password-store) instead gnome-keyring for storing passwords. I received a reply indicating they use this project, node-keytar, and to send here this feature request.

## Motivation

Seems password store has more linux philosophy, open source, and git support to external sync without dependency to third party servers - for instance, bitwarden.

## Describe alternatives you've considered

Thunderbird has an add-on, but was discontinued. Maybe its not so popular at all. For many web browsers this integration exists.

## Additional context

Thank you very much to allow me to send you this idea. Its only a suggestion and could be or not to be a good feature request.

**Comment by shiftkey** [comment]
@helionmelion can you provide more information about what "pass" is? It's really hard to Google for, and will help me to better understand this request...

**Comment by helionmelion** [comment]
> @helionmelion can you provide more information about what "pass" is? It's really hard to Google for, and will help me to better understand this request...

Sorry about the lack of information. 
The project site is: 
https://www.passwordstore.org/

This name "pass" and the long format name "password store" choosen by its author (zx2c4) is too much generic indeed.
 It uses GPG and supports third-party clients, like GUI. Using git, the user can make backup, cloning it to the cloud.

This wiki page give us a overall comparison about password managers characteristics.
https://en.wikipedia.org/wiki/List_of_password_managers

Thanks for reply and glad to help with this information.

**Comment by shiftkey** [comment]
So I'll add some more context about what `keytar` is doing under the hood:

 - we use `libsecret` to query for passwords - [source here](https://github.com/atom/node-keytar/blob/master/src/keytar_posix.cc)
 - we ported to `libsecret` from `gnome-keyring` in https://github.com/atom/node-keytar/pull/63 because we didn't want to be tied to a specific backend
 - `gnome-keyring` seems to be the only implementation I'm aware of for Linux currently, even after all this time
 - KDE systems do not seem to support this, based on the last time I checked https://github.com/atom/node-keytar/issues/74#issuecomment-456153037
 - I don't have plans to support custom backends currently, because the goal here was not to be tied to a specific backend

**Comment by helionmelion** [comment]
> I don't have plans to support custom backends currently, because the goal here was not to be tied to a specific backend

I understand, but thank you for your attention in bring here a explanation about keytar!

**Comment by shiftkey** [comment]
Closing this out for now as it's not something we plan to support in the future

**Comment by WhyNotHugo** [comment]
Actually, libsecret is just a library that uses a standard spec for exposing passwords.

gnome-keyring is one backend, but there's also one for [`pass`](https://github.com/mdellweg/pass_secret_service/) (I'm pretty sure I also saw another one, but the name **is** hard to google!).
