### ISSUE TITLE
Possibility of adding support for iOS and Android

### ISSUE THREAD

**Issue by jg123** [atom/node-keytar#42]
How possible would it be to add support for the iOS keychain and the Android keystore by way of react-native?

**Comment by shiftkey** [comment]
I'm honestly not sure how React Native handles native Node modules, and a quick skim of some resources didn't really help me to understand further.

If someone knows how to do it, I'd love to hear more and see what's possible.

**Comment by shiftkey** [comment]
@jg123 I'm going to close this out as I don't believe I can support this in `keytar` for a few reasons:

 - the examples for [iOS](https://facebook.github.io/react-native/docs/native-modules-ios) and [Android](https://facebook.github.io/react-native/docs/native-modules-android) are written in Java and ObjectiveC, which are different to the plain C++ we have currently in the project
 - we leverage `nan` in a lot of places to make cross-platform support consistent, but it looks like native modules in React Native requires handrolling a lot of platform-specific code for interop
 - the toolchain for supporting this is very different to what we support in `keytar` - instead of using `node-gyp` and a `binding.gyp`, you need to setup Gradle and XCode projects to build for each platform
 - this isn't an area I'm familiar with, and don't have bandwidth to skill up on in the near future

If someone however wants to take a shot at this to see if they can get something working, go for it. But I don't think we can leverage much of what's in here to target React Native, which seems to be where the initial question was heading.
