### ISSUE TITLE
Problem on Ubuntu 16.04 with Unity

### ISSUE THREAD

**Issue by step21** [atom/node-keytar#73]
Using Nylas, I cannot get it to work because of keytar. All other apps work fine. See also https://github.com/nylas-mail-lives/nylas-mail/issues/51 for details.
Both libsecret and gnome-keyring are installed as required. Is it possible to somehow check libsecret for basic functionality or is my configuration (Ubuntu 16.04 with Unity) not supported? Other apps that require libsecret work fine.

**Comment by shiftkey** [comment]
@step21 apologies for the delay in replying.

I think you'd need to check your machine setup, because the message in here suggests that there's nothing responding to the message sent by the app:

```
Gkr-Message: secret service operation failed: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

This comment has a relevant snippet to ensure that you have the `gnome-keyring-daemon` running that might have been the missing piece: https://github.com/atom/node-keytar/issues/132#issuecomment-444159414
